version: '3.8'

services:
  # Flask后端服务
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      # 数据库配置
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=dota_analysis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # Redis配置
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # 安全配置
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      # API密钥
      - OPENDOTA_API_KEY=${OPENDOTA_API_KEY}
      - STRATZ_API_KEY=${STRATZ_API_KEY}
      - STEAM_API_KEY=${STEAM_API_KEY}
      # OSS配置
      - ALIYUN_ACCESS_KEY_ID=${ALIYUN_ACCESS_KEY_ID}
      - ALIYUN_ACCESS_KEY_SECRET=${ALIYUN_ACCESS_KEY_SECRET}
      - ALIYUN_OSS_ENDPOINT=${ALIYUN_OSS_ENDPOINT}
      - ALIYUN_OSS_BUCKET=${ALIYUN_OSS_BUCKET}
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ../../config.yaml:/app/config.yaml:ro  # 挂载配置文件
      - ../../dem2json:/app/dem2json:ro         # 挂载DEM解析工具
    restart: unless-stopped
    networks:
      - dota-network

  # PostgreSQL数据库
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=dota_analysis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - dota-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - dota-network

  # Celery工作进程
  celery-worker:
    build: .
    command: celery -A tasks.data_sync.celery worker --loglevel=info
    environment:
      - FLASK_ENV=production
      # 数据库配置
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=dota_analysis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # Redis配置
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # 安全配置
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      # API密钥
      - OPENDOTA_API_KEY=${OPENDOTA_API_KEY}
      - STRATZ_API_KEY=${STRATZ_API_KEY}
      - STEAM_API_KEY=${STEAM_API_KEY}
      # OSS配置
      - ALIYUN_ACCESS_KEY_ID=${ALIYUN_ACCESS_KEY_ID}
      - ALIYUN_ACCESS_KEY_SECRET=${ALIYUN_ACCESS_KEY_SECRET}
      - ALIYUN_OSS_ENDPOINT=${ALIYUN_OSS_ENDPOINT}
      - ALIYUN_OSS_BUCKET=${ALIYUN_OSS_BUCKET}
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs
      - ../../config.yaml:/app/config.yaml:ro  # 挂载配置文件
      - ../../dem2json:/app/dem2json:ro         # 挂载DEM解析工具
    restart: unless-stopped
    networks:
      - dota-network

  # Celery定时任务调度器
  celery-beat:
    build: .
    command: celery -A tasks.data_sync.celery beat --loglevel=info
    environment:
      - FLASK_ENV=production
      # 数据库配置
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=dota_analysis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # Redis配置
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # 安全配置
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      # API密钥
      - OPENDOTA_API_KEY=${OPENDOTA_API_KEY}
      - STRATZ_API_KEY=${STRATZ_API_KEY}
      - STEAM_API_KEY=${STEAM_API_KEY}
      # OSS配置
      - ALIYUN_ACCESS_KEY_ID=${ALIYUN_ACCESS_KEY_ID}
      - ALIYUN_ACCESS_KEY_SECRET=${ALIYUN_ACCESS_KEY_SECRET}
      - ALIYUN_OSS_ENDPOINT=${ALIYUN_OSS_ENDPOINT}
      - ALIYUN_OSS_BUCKET=${ALIYUN_OSS_BUCKET}
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs
      - ../../config.yaml:/app/config.yaml:ro  # 挂载配置文件
    restart: unless-stopped
    networks:
      - dota-network

  # Flower监控界面（可选）
  flower:
    build: .
    command: celery -A tasks.data_sync.celery flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - dota-network

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
      - ../frontend:/usr/share/nginx/html:ro
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - dota-network

volumes:
  postgres_data:
  redis_data:

networks:
  dota-network:
    driver: bridge
